// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWLwpS3boKQu_11Ku4q3IaXx_CYbFR9A',
    appId: '1:401496379965:web:0bb41e9b135c82f2489054',
    messagingSenderId: '401496379965',
    projectId: 'phants-notes',
    authDomain: 'phants-notes.firebaseapp.com',
    storageBucket: 'phants-notes.appspot.com',
    measurementId: 'G-K2Y0Z703HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACMPiv5o9I5PC16hgE0lIVvNQ_O78I9jw',
    appId: '1:401496379965:android:05e2695673e95707489054',
    messagingSenderId: '401496379965',
    projectId: 'phants-notes',
    storageBucket: 'phants-notes.appspot.com',
  );
}
